require('Blocks/common')

FillBlock("OreWasher", require('Blocks/ore_washer'))
FillBlock("Macerator", require('Blocks/macerator'))
FillBlock("CuttingMachine", require('Blocks/cutting_machine'))
FillBlock("Fermenter", require('Blocks/fermenter'))
FillBlock("AutomaticHammer", require('Blocks/automatic_hammer'))
FillBlock("StirlingEngine", require('Blocks/stirling_engine'))
FillBlock("CompactGenerator", require('Blocks/compact_generator'))
FillBlock("Smelter", require('Blocks/smelter'))
FillBlock("Furnace", require('Blocks/furnace'))
FillBlock("Destroyer", require('Blocks/destroyer'))
FillBlock("Assembler", require('Blocks/assembler'))
FillBlock("Oven", require('Blocks/oven'))
FillBlock("BlastFurnace", require('Blocks/blast_furnace'))
FillBlock("AutomaticFarm", require('Blocks/automatic_farm'))
FillBlock("AtmosphericCondenser", require('Blocks/atmospheric_condenser'))
FillBlock("Boiler", require('Blocks/boiler'))