require('Blocks/common')

fill_block("OreWasher", require('Blocks/ore_washer'))
fill_block("Macerator", require('Blocks/macerator'))
fill_block("CuttingMachine", require('Blocks/cutting_machine'))
fill_block("Fermenter", require('Blocks/fermenter'))
fill_block("AutomaticHammer", require('Blocks/automatic_hammer'))
fill_block("StirlingEngine", require('Blocks/stirling_engine'))
fill_block("CompactGenerator", require('Blocks/compact_generator'))
fill_block("Smelter", require('Blocks/smelter'))
fill_block("Furnace", require('Blocks/furnace'))
fill_block("Destroyer", require('Blocks/destroyer'))
fill_block("Assembler", require('Blocks/assembler'))
fill_block("Oven", require('Blocks/oven'))
fill_block("BlastFurnace", require('Blocks/blast_furnace'))